package com.softwareEngineering.Freelancer.platform.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Entity // want to have a database entity of this class called categories
@Table(name = "categories")
public class Category {
    @Setter //autogenerated setter getter
    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Setter
    @Getter
    @Column
    private String categoryName;

    @ManyToMany(mappedBy = "categories")
    @Setter
    @Getter
    private List<ServiceProvider> serviceProviders=new ArrayList<ServiceProvider>();

    @ManyToMany(mappedBy = "relatedCategories")
    @Setter
    @Getter
    private List<ServiceRequest> serviceRequests=new ArrayList<ServiceRequest>();

    public Category(String categoryName) {
        this.categoryName = categoryName;
    }
    public Category() {}

    @Override
    public String toString() {
        return "categoryName='" + categoryName + '\'';
    }
}
